### ISSUE TITLE
How is frontmatter distinguished from normal content?

### ISSUE THREAD

**Issue by koraa** [remarkjs/remark-frontmatter#8]
Compiling the markdown

```
---
Hello
---
```

yields the AST (represented as yaml; position info stripped)

```
type: root
children:
- type: thematicBreak
- type: paragraph
  children:
  - type: text
    value: Hello
- type: thematicBreak
```

Despite "Hello" being valid yaml, this does indeed match my intuition about how frontmatter should work!
How does this project distinguish between proper frontmatter and normal markdown text?
